name: webviewtube
description: Play YouTube videos using the IFrame Player API with Flutter official support of WebView.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
